services:
  windows:
    image: dockurr/windows
    container_name: win10
    environment:
      VERSION: "10"
      LANGUAGE: "Chinese"
      DISK_SIZE: "200G"
      RAM_SIZE: "32G"
      CPU_CORES: "16"
      USERNAME: "username"
      PASSWORD: "passwork"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /var/win:/storage
